### ISSUE TITLE
Oferta de emprego voluntário

### ISSUE THREAD

**Issue by brunoha-zz** [androiddevbr-cwb/grupo-de-estudos#9]
Aplicativo que liste e una tanto ofertas de trabalho voluntários (em ONGs, por exemplo) quanto pessoas dispostas prestar esses serviços.

**Comment by gustavobite** [comment]
Essa ideia partiu desse link:
http://ideias.rioapps.com.br/ideias/822

Ideia:
Eu gostaria de um aplicativo que através de um mapa, permitisse a visualização dos projetos sociais ativos na cidade de Curitiba. Alimentado também pelos próprios projetos, o app disponibilizaria informações sobre as ONGs, como público atendido, serviços oferecidos e necessidades. Facilitando desse modo a interação entre os projetos e o conhecimento, por parte dos cidadãos, da dimensão do serviço social na cidade.

**Comment by gustavobite** [comment]
MVP:
- Login
- Cadastro Usuário 
- Cadastro Organização
- Cadastro de anúncios dentro de cada organização
- Listagem de organizações
- Detalhes da organização com seu feed
- Seguir a organização para receber push notifications

Stack:
- Firebase (Auth, Functions, Notifications, Firestore, Storage)
- Kotlin
- Koin
- MVVM
- Android Architecture Components
- Material IO
- Glide
Testes:
- Mockito
- Junit
- Roboletric

- TravisCI

**Comment by diefferson** [comment]
https://github.com/androiddevbr-cwb/cidadaodebem

**Comment by diefferson** [comment]
Projeto iniciado, fechando issue;
